# Generated by Django 3.2.25 on 2025-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('admin_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_notificationdate', models.DateField()),
                ('admin_notification_time', models.TimeField()),
                ('admin_notification', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'admin_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_time', models.TimeField()),
                ('notification_date', models.DateField()),
                ('notification', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
    ]
