# Generated by Django 3.2.25 on 2025-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoVideo',
            fields=[
                ('pv_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('pv_date', models.DateField()),
                ('pv_time', models.TimeField()),
                ('pv', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'photo_video',
                'managed': False,
            },
        ),
    ]
