# Generated by Django 3.2.25 on 2025-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('calender_id', models.AutoField(primary_key=True, serialize=False)),
                ('calender_date', models.DateField()),
                ('calender_description', models.CharField(max_length=100)),
                ('calender_time', models.TimeField()),
                ('calender_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'calender',
                'managed': False,
            },
        ),
    ]
