# Generated by Django 3.2.25 on 2025-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_date', models.DateField()),
                ('chat_time', models.TimeField()),
                ('student_id', models.IntegerField()),
                ('faculty_id', models.IntegerField()),
                ('chat', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
    ]
