# Generated by Django 3.2.25 on 2025-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_date', models.DateField()),
                ('complaint_time', models.TimeField()),
                ('complaint', models.CharField(max_length=100)),
                ('complaint_replay', models.CharField(max_length=100)),
                ('complaint_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
