# Generated by Django 3.2.25 on 2025-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_duration', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
    ]
