# Generated by Django 3.2.25 on 2025-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('faculty_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
    ]
