# Generated by Django 3.2.25 on 2025-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_date', models.DateField()),
                ('study_material', models.CharField(max_length=300)),
                ('study_time', models.TimeField()),
                ('study_materialdes', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'study_material',
                'managed': False,
            },
        ),
    ]
