# Generated by Django 3.2.25 on 2025-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_age', models.IntegerField()),
                ('student_gender', models.CharField(max_length=50)),
                ('student_phone', models.IntegerField()),
                ('student_email', models.CharField(max_length=100)),
                ('student_photo', models.CharField(max_length=500)),
                ('student_username', models.CharField(max_length=100)),
                ('student_password', models.IntegerField()),
                ('course', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
